// Centralized image path constants for better organization and maintenance
// This file acts as an index for all image paths used throughout the application

// Import existing logos from src/assets (parent directory)
import mpLogoPrimary from '../mp_logo.png';
import mpLogoCircle from '../mp_logo-CIRCLE.png';
import blackLogo from '../black_logo.png';

// Export the logo imports
export { mpLogoPrimary, mpLogoCircle, blackLogo };

// Event Images - now properly organized in events folder
export const eventImages = {
  studySession1: '/webapp/assets/images/events/studysession/studysession1.png',
  studySession2: '/webapp/assets/images/events/studysession/studysession2.png',
} as const;

// Home Carousel Images - AUTO-UPDATED! 🚀
// All images from: public/assets/images/events/homecaroussel/
// Just drop new JPG/PNG files in the folder and they'll appear automatically!
export const homeCarouselImages = [
  '/webapp/assets/images/events/homecaroussel/!home (6).jpg',
  '/webapp/assets/images/events/homecaroussel/home (1).jpeg',
  '/webapp/assets/images/events/homecaroussel/home (1).JPG',
  '/webapp/assets/images/events/homecaroussel/home (2).JPG',
  '/webapp/assets/images/events/homecaroussel/home (3).JPG',
  '/webapp/assets/images/events/homecaroussel/home (4).JPG',
  '/webapp/assets/images/events/homecaroussel/home (5).JPG',
  '/webapp/assets/images/events/homecaroussel/home (7).JPG',
  '/webapp/assets/images/events/homecaroussel/home (8).JPG',
  '/webapp/assets/images/events/homecaroussel/home (9).JPG',
  // 🎯 TO ADD NEW IMAGES: Just drop JPG/PNG files in the homecaroussel folder
  // and add the path here following the pattern above
] as const;

// Event galleries - year-round events first, then chronological
export const eventGalleries = {
  // Year-round recurring events
  studySession_10_09_2024: {
    title: "study_sessions_title",
    subtitle: "study_sessions_date",
    description: "study_sessions_desc",
    images: [
      '/webapp/assets/images/events/studysession/studysession1.png',
      '/webapp/assets/images/events/studysession/studysession2.png',
    ],
  },
  guestLectures_11_14_2025: {
    title: "guest_lectures_title",
    subtitle: "guest_lectures_date",
    description: "guest_lectures_desc",
    images: [
      '/webapp/assets/images/events/guestlectures/!COVER.jpeg',
      '/webapp/assets/images/events/guestlectures/2.jpeg',
      '/webapp/assets/images/events/guestlectures/3.jpeg',
      '/webapp/assets/images/events/guestlectures/4.jpeg',
      '/webapp/assets/images/events/guestlectures/5.jpeg',
      '/webapp/assets/images/events/guestlectures/7.jpeg',
      '/webapp/assets/images/events/guestlectures/9.jpeg',
      '/webapp/assets/images/events/guestlectures/WhatsApp Image 2025-11-14 at 22.10.04.jpeg',
    ],
  },
  examPreps_12_2025: {
    title: "exam_preps_title",
    subtitle: "exam_preps_date",
    description: "exam_preps_desc",
    images: [
      '/webapp/assets/images/events/exampreps/exampreps (1).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (2).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (3).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (4).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (5).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (6).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (7).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (8).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (9).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (10).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (11).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (12).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (13).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (14).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (15).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (16).jpeg',
      '/webapp/assets/images/events/exampreps/exampreps (17).jpeg',
    ],
  },
  // Academic year 2024-2025 specific events (chronological order)
  mexicanDinner_12_09_2025: {
    title: "mexican_dinner_title",
    subtitle: "mexican_dinner_date",
    description: "mexican_dinner_desc",
    images: [
      '/webapp/assets/images/events/mexicandinner/1Image 2025-09-14 at 13.03.07_09060e7e.jpg',
      '/webapp/assets/images/events/mexicandinner/IMG_9545.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9548.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9549.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9550.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9551.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9552.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9553.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9554.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9555.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9556.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9557.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9558.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9560.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9561.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9562.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9563.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9564.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9565.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9566.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9567.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9570.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9571.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9572.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9576.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9577.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9578.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9580.JPG',
      '/webapp/assets/images/events/mexicandinner/IMG_9582.JPG',
      '/webapp/assets/images/events/mexicandinner/didyoucheckin.jpg',
    ],
  },
  pumpkinCarving_10_2025: {
    title: "pumpkin_carving_title",
    subtitle: "pumpkin_carving_date",
    description: "pumpkin_carving_desc",
    images: [
      '/webapp/assets/images/events/pumpkincarving/! cover.jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (1).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (2).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (3).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (4).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (5).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (6).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (7).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (8).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (9).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (11).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (12).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (13).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (14).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (15).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (16).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (17).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (18).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (19).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (20).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (21).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (22).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (23).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (24).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (25).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (27).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (28).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (29).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (30).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (31).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (32).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (33).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (34).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (35).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (36).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (37).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (38).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (39).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (42).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (43).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (44).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (45).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (46).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (47).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (48).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (49).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (51).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (52).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (53).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (54).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (55).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (57).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (58).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (59).jpg',
      '/webapp/assets/images/events/pumpkincarving/1 (64).jpg',
    ],
  },
  hackathon_11_2025: {
    title: "hackathon_title",
    subtitle: "hackathon_date",
    description: "hackathon_desc",
    images: [
      '/webapp/assets/images/events/hackathon/1.jpeg',
      '/webapp/assets/images/events/hackathon/2.jpeg',
      '/webapp/assets/images/events/hackathon/3.jpeg',
    ],
  },
  halloweenClub_10_28_2025: {
    title: "halloween_club_title",
    subtitle: "halloween_club_date",
    description: "halloween_club_desc",
    images: [
      '/webapp/assets/images/events/halloweenclub/1.jpeg',
      '/webapp/assets/images/events/halloweenclub/2.jpeg',
      '/webapp/assets/images/events/halloweenclub/3.jpeg',
      '/webapp/assets/images/events/halloweenclub/4.jpeg',
      '/webapp/assets/images/events/halloweenclub/5.jpeg',
      '/webapp/assets/images/events/halloweenclub/6.jpeg',
      '/webapp/assets/images/events/halloweenclub/7.jpeg',
      '/webapp/assets/images/events/halloweenclub/8.jpeg',
      '/webapp/assets/images/events/halloweenclub/9.jpeg',
      '/webapp/assets/images/events/halloweenclub/10.jpeg',
      '/webapp/assets/images/events/halloweenclub/11.jpeg',
      '/webapp/assets/images/events/halloweenclub/12.jpeg',
      '/webapp/assets/images/events/halloweenclub/13.jpeg',
      '/webapp/assets/images/events/halloweenclub/14.jpeg',
      '/webapp/assets/images/events/halloweenclub/15.jpeg',
      '/webapp/assets/images/events/halloweenclub/16.jpeg',
    ],
  },
  gameNight_11_07_2025: {
    title: "game_night_title",
    subtitle: "game_night_date",
    description: "game_night_desc",
    images: [
      '/webapp/assets/images/events/gamenight/1.jpeg',
      '/webapp/assets/images/events/gamenight/2.jpeg',
      '/webapp/assets/images/events/gamenight/3.jpeg',
      '/webapp/assets/images/events/gamenight/4.jpeg',
      '/webapp/assets/images/events/gamenight/5.jpeg',
      '/webapp/assets/images/events/gamenight/6.jpeg',
      '/webapp/assets/images/events/gamenight/7.jpeg',
      '/webapp/assets/images/events/gamenight/8.jpeg',
      '/webapp/assets/images/events/gamenight/9.jpeg',
      '/webapp/assets/images/events/gamenight/10.jpeg',
      '/webapp/assets/images/events/gamenight/11.jpeg',
    ],
  },
  pancakeBoat_12_04_2025: {
    title: "pancake_boat_title",
    subtitle: "pancake_boat_date",
    description: "pancake_boat_desc",
    images: [
      '/webapp/assets/images/events/pancakeboat/1.jpeg',
      '/webapp/assets/images/events/pancakeboat/2.jpeg',
      '/webapp/assets/images/events/pancakeboat/3.jpeg',
      '/webapp/assets/images/events/pancakeboat/IMG_5403.jpg',
      '/webapp/assets/images/events/pancakeboat/IMG_5406.jpg',
      '/webapp/assets/images/events/pancakeboat/IMG_5409.jpg',
    ],
  },
  iceSkating_01_21_2026: {
    title: "ice_skating_title",
    subtitle: "ice_skating_date",
    description: "ice_skating_desc",
    images: [
      '/webapp/assets/images/events/iceskating/&cover.jpg',
      '/webapp/assets/images/events/iceskating/iceskating (1).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (2).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (6).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (7).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (8).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (10).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (11).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (13).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (17).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (18).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (22).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (27).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (28).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (30).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (31).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (32).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (33).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (36).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (37).jpg',
      '/webapp/assets/images/events/iceskating/iceskating (41).jpg',
    ],
  },
  airDryClayWorkshop_02_05_2026: {
    title: "air_dry_clay_title",
    subtitle: "air_dry_clay_date",
    description: "air_dry_clay_desc",
    images: [
      '/webapp/assets/images/events/airdryclayworkshop/clay (1).JPEG',
      '/webapp/assets/images/events/airdryclayworkshop/clay (1).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (2).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (3).JPEG',
      '/webapp/assets/images/events/airdryclayworkshop/clay (3).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (4).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (5).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (6).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (10).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (16).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (28).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (30).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (31).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (36).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (38).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (39).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (40).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (41).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (42).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (43).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (44).jpg',
      '/webapp/assets/images/events/airdryclayworkshop/clay (45).jpg',
    ],
  },
  valentineDinner_02_13_2026: {
    title: "valentine_dinner_title",
    subtitle: "valentine_dinner_date",
    description: "valentine_dinner_desc",
    images: [
      '/webapp/assets/images/events/valentinedinner/3.jpeg',
      '/webapp/assets/images/events/valentinedinner/4.jpeg',
      '/webapp/assets/images/events/valentinedinner/5.jpeg',
      '/webapp/assets/images/events/valentinedinner/valentines (1).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (2).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (3).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (4).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (5).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (6).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (7).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (8).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (9).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (10).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (11).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (14).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (15).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (18).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (19).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (20).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (22).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (24).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (25).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (26).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (27).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (28).jpg',
      '/webapp/assets/images/events/valentinedinner/valentines (29).jpg',
    ],
  },
  highTeaAndBraceletMaking_03_06_2026: {
    title: "high_tea_title",
    subtitle: "high_tea_date",
    description: "high_tea_desc",
    images: [
      '/webapp/assets/images/events/highteaandbraceletmaking/high (1).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (2).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (3).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (4).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (5).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (6).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (7).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (8).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (9).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (10).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (11).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (12).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (13).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (14).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (15).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (16).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (17).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (18).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (19).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (20).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (21).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (22).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (23).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (24).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (25).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (26).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (27).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (28).jpg',
      '/webapp/assets/images/events/highteaandbraceletmaking/high (29).jpg',
    ],
  },
  cyberSecurityWorkshop_03_09_2026: {
    title: "cyber_security_title",
    subtitle: "cyber_security_date",
    description: "cyber_security_desc",
    images: [
      '/webapp/assets/images/events/cybersecurityworkshop/cyber (1).jpeg',
      '/webapp/assets/images/events/cybersecurityworkshop/cyber (2).jpeg',
      '/webapp/assets/images/events/cybersecurityworkshop/cyber (3).jpeg',
      '/webapp/assets/images/events/cybersecurityworkshop/cyber (4).jpeg',
    ],
  },
  goKartingAndLaserTag_03_13_2026: {
    title: "go_karting_lasertag_title",
    subtitle: "go_karting_lasertag_date",
    description: "go_karting_lasertag_desc",
    images: [
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (1).jpeg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (2).jpeg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (3).jpeg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (1).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (2).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (3).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (4).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (5).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (6).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (7).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (8).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (9).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (10).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (11).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (12).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (13).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (14).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (15).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (16).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (17).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (18).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (19).JPG',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (20).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (21).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (22).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (23).jpg',
      '/webapp/assets/images/events/gokartingandlasertag/kartinglaser (24).jpg',
    ],
  },
  toteBagPainting_04_02_2026: {
    title: "tote_bag_painting_title",
    subtitle: "tote_bag_painting_date",
    description: "tote_bag_painting_desc",
    images: [
      '/webapp/assets/images/events/totebagpainting/totebag (1).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (2).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (3).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (4).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (5).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (6).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (7).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (8).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (9).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (10).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (11).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (12).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (13).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (14).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (15).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (16).jpeg',
      '/webapp/assets/images/events/totebagpainting/totebag (17).jpeg',
    ],
  },
  escapeRoom_04_10_2026: {
    title: "escape_room_title",
    subtitle: "escape_room_date",
    description: "escape_room_desc",
    images: [
      '/webapp/assets/images/events/escaperoom/escaperoom (1).jpg',
      '/webapp/assets/images/events/escaperoom/escaperoom (2).jpg',
      '/webapp/assets/images/events/escaperoom/escaperoom (3).jpg',
      '/webapp/assets/images/events/escaperoom/escaperoom (4).jpg',
      '/webapp/assets/images/events/escaperoom/escaperoom (5).jpg',
      '/webapp/assets/images/events/escaperoom/escaperoom (6).jpg',
    ],
  },
  // Easy to add new event categories:
  // socialEvents: {
  //   title: "social_events",
  //   description: "social_events_desc",
  //   images: [
  //     '/webapp/assets/images/events/social/event1.png',
  //     '/webapp/assets/images/events/social/event2.png',
  //   ],
  // },
  // workshops: {
  //   title: "workshops", 
  //   description: "workshops_desc",
  //   images: [
  //     '/webapp/assets/images/events/workshops/workshop1.png',
  //   ],
  // },
} as const;

// Team Photos - now properly organized in team folder
export const teamPhotos = {
  vitor: '/webapp/assets/images/team/vitor.png',
  noor: '/webapp/assets/images/team/noor.png',
  goncalo: '/webapp/assets/images/team/goncalo.png',
  nox: '/webapp/assets/images/team/nox.png',
  anastasia: '/webapp/assets/images/team/anastasia.png',
  mariana: '/webapp/assets/images/team/mariana.png',
  gin: '/webapp/assets/images/team/gin.png',
  defaultPerson: '/webapp/assets/images/team/default person.jpg',
} as const;

export const teamSongs = {
  vitorSong: '/webapp/assets/images/team/vitorSong.mp3',
  noorSong: '/webapp/assets/images/team/noorSong.mp3',
  goncaloSong: '/webapp/assets/images/team/goncaloSong.mp3',
  noxSong: '/webapp/assets/images/team/noxSong.mp3',
  anastasiaSong: '/webapp/assets/images/team/anastasiaSong.mp3',
  marianaSong: '/webapp/assets/images/team/marianaSong.mp3',
  ginSong: '/webapp/assets/images/team/ginSong.mp3',
} as const;

// Asset organization paths - now implemented!
export const ASSET_PATHS = {
  images: {
    events: '/webapp/assets/images/events/',
    team: '/webapp/assets/images/team/',
    logos: '/webapp/assets/images/logos/',
  },
  sounds: {
    games: '/webapp/assets/sounds/games/',
  },
} as const;

// Organized logo paths
export const logoImages = {
  primary: '/webapp/assets/images/logos/mp_logo-CIRCLE.png',
  black: '/webapp/assets/images/logos/black_logo.png',
} as const;

// Seagull mascot images
export const seagullImages = {
  normal: '/webapp/assets/images/logos/seagullimages/normalseagul.png',
  chipInMouth: '/webapp/assets/images/logos/seagullimages/seagulchipinmouth.png',
  confused: '/webapp/assets/images/logos/seagullimages/seagullconfused.png',
  sad: '/webapp/assets/images/logos/seagullimages/seagullsad.png',
  starEyes: '/webapp/assets/images/logos/seagullimages/seagullwithstareyes.png',
} as const;
